import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import { CartProvider } from '@/utils/CardContext';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Header from "./components/layout/Header";
import { Col, Row } from 'antd';
import '@ant-design/v5-patch-for-react-19';
const urbanist = Urbanist({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${urbanist.className}`}>
        <AntdRegistry>
          <CartProvider>
            <Header />
            <main>
              <Row justify={"center"}>
                <Col md={22}>
                  {children}

                </Col>
              </Row>
            </main>
          </CartProvider>

        </AntdRegistry>
      </body>
    </html>
  );
}
