import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Header from "./components/layout/Header";

const urbanist = Urbanist({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${urbanist.className}`}>
        <AntdRegistry>
          <Header/>
          <main>
            {children}
          </main>
        </AntdRegistry>
      </body>
    </html>
  );
}
